const data = [
   {
      listingID: 1,
      donorID: 1,
      postTime: '39m ago',
      donationName: 'Pancit Canton Noodles',
      donationNote: '10 pieces',
      donationCategory: 'Instant Noodles',
      donationQuantity: '10',
      donationExpiry: 'July 05, 2021',
      pickupDate: 'June 25, 2021',
      pickupLoc:
         'National University-Manila, M.F. Jhocson Street, Sampaloc, Manila, Metro Manila',
      distance: '300m away',
      imgLoc: 'https://c1.staticflickr.com/5/4158/33593402264_bedafb79d1_c.jpg',
   },
   {
      listingID: 2,
      donorID: 2,
      postTime: '1h ago',
      donationName: 'Argentina Corned Beef',
      donationNote: '10 pieces',
      donationCategory: 'Instant Noodles',
      donationQuantity: '10',
      donationExpiry: 'July 05, 2021',
      pickupDate: 'June 25, 2021',
      pickupLoc:
         'National University-Manila, M.F. Jhocson Street, Sampaloc, Manila, Metro Manila',
      distance: '350m away',
      imgLoc: 'https://cf.shopee.com.my/file/9e0aec8c671eaaa75d039ddad2efce47',
   },
   {
      listingID: 3,
      donorID: 3,
      postTime: '1h ago',
      donationName: 'Choco chip cookies',
      donationNote: '10 pieces',
      donationCategory: 'Instant Noodles',
      donationQuantity: '10',
      donationExpiry: 'July 05, 2021',
      pickupDate: 'June 25, 2021',
      pickupLoc:
         'National University-Manila, M.F. Jhocson Street, Sampaloc, Manila, Metro Manila',
      distance: '1km away',
      imgLoc:
         'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRypXmWWFQagZnc-n-t99y2yAJRBZ2tkWCzKA&usqp=CAU',
   },
   {
      listingID: 4,
      donorID: 4,
      postTime: '1h ago',
      donationName: 'Lucky Me Chicken',
      donationNote: '10 pieces',
      donationCategory: 'Instant Noodles',
      donationQuantity: '10',
      donationExpiry: 'July 05, 2021',
      pickupDate: 'June 25, 2021',
      pickupLoc:
         'National University-Manila, M.F. Jhocson Street, Sampaloc, Manila, Metro Manila',
      distance: '1km away',
      imgLoc: 'https://cf.shopee.com.my/file/71ee574d1013a3715f71a25244c8715c',
   },
   {
      listingID: 5,
      donorID: 5,
      postTime: '2h ago',
      donationName: 'Sky Flakes',
      donationNote: '10 pieces',
      donationCategory: 'Instant Noodles',
      donationQuantity: '10',
      donationExpiry: 'July 05, 2021',
      pickupDate: 'June 25, 2021',
      pickupLoc:
         'National University-Manila, M.F. Jhocson Street, Sampaloc, Manila, Metro Manila',
      distance: '500m away',
      imgLoc: 'https://cf.shopee.ph/file/b6fe5dbf2a4ff8d77959296a3574d630_tn',
   },
   {
      listingID: 6,
      donorID: 6,
      postTime: '2h ago',
      donationName: 'Frabelle Burger Patties',
      donationNote: '10 pieces',
      donationCategory: 'Instant Noodles',
      donationQuantity: '10',
      donationExpiry: 'July 05, 2021',
      pickupDate: 'June 25, 2021',
      pickupLoc:
         'National University-Manila, M.F. Jhocson Street, Sampaloc, Manila, Metro Manila',
      distance: '400m away',
      imgLoc:
         'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoU1jCEe2bDwULGz--EA-gKsgyhanLMv4VzVVb8u5guX4yoBwRSgab-xVUF00azThf04s&usqp=CAU',
   },
   {
      listingID: 7,
      donorID: 7,
      postTime: '2h ago',
      donationName: 'Tender Juicy Hotdog',
      donationNote: '10 pieces',
      donationCategory: 'Instant Noodles',
      donationQuantity: '10',
      donationExpiry: 'July 05, 2021',
      pickupDate: 'June 25, 2021',
      pickupLoc:
         'National University-Manila, M.F. Jhocson Street, Sampaloc, Manila, Metro Manila',
      distance: '350m away',
      imgLoc:
         'https://www.bestsellermeats.com/wp-content/uploads/2020/04/DSC_4062-scaled.jpg',
   },
   {
      listingID: 8,
      donorID: 8,
      postTime: '2h ago',
      donationName: 'Rebisco choco',
      donationNote: '10 pieces',
      donationCategory: 'Instant Noodles',
      donationQuantity: '10',
      donationExpiry: 'July 05, 2021',
      pickupDate: 'June 25, 2021',
      pickupLoc:
         'National University-Manila, M.F. Jhocson Street, Sampaloc, Manila, Metro Manila',
      distance: '2km away',
      imgLoc:
         'https://ph-test-11.slatic.net/p/5c1394e9c44e4898adbfe6341e2d9ba4.jpg_720x720q80.jpg_.webp',
   },
   {
      listingID: 9,
      donorID: 9,
      postTime: '3h ago',
      donationName: 'Lucky Me Pancit Canton Noodles',
      donationNote: '10 pieces',
      donationCategory: 'Instant Noodles',
      donationQuantity: '10',
      donationExpiry: 'July 05, 2021',
      pickupDate: 'June 25, 2021',
      pickupLoc:
         'National University-Manila, M.F. Jhocson Street, Sampaloc, Manila, Metro Manila',
      distance: '3km away',
      imgLoc:
         'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDTG13NcPEnb81cuVldpcBjlLRjyUkzVhWJIQ68fqV43ly8MMapt4KQiBOAbOq0eedEpo&usqp=CAU',
   },
   {
      listingID: 10,
      donorID: 10,
      postTime: '1h ago',
      donationName: 'Hunts Pork and Beans',
      donationNote: '10 pieces',
      donationCategory: 'Instant Noodles',
      donationQuantity: '10',
      donationExpiry: 'July 05, 2021',
      pickupDate: 'June 25, 2021',
      pickupLoc:
         'National University-Manila, M.F. Jhocson Street, Sampaloc, Manila, Metro Manila',
      distance: '350m away',
      imgLoc:
         'https://media.karousell.com/media/photos/products/2020/9/17/hunts_pork_and_beans_original__1600328765_688eec1a',
   },
   {
      listingID: 11,
      donorID: 11,
      postTime: '1h ago',
      donationName: 'Butter Sticks',
      donationNote: '10 pieces',
      donationCategory: 'Instant Noodles',
      donationQuantity: '10',
      donationExpiry: 'July 05, 2021',
      pickupDate: 'June 25, 2021',
      pickupLoc:
         'National University-Manila, M.F. Jhocson Street, Sampaloc, Manila, Metro Manila',
      distance: '350m away',
      imgLoc:
         'https://ph-test-11.slatic.net/p/abada0fd5d956a99f99d0f2ebebdd974.jpg',
   },
   {
      listingID: 12,
      donorID: 12,
      postTime: '1h ago',
      donationName: '555 Sardines',
      donationNote: '10 pieces',
      donationCategory: 'Instant Noodles',
      donationQuantity: '10',
      donationExpiry: 'July 05, 2021',
      pickupDate: 'June 25, 2021',
      pickupLoc:
         'National University-Manila, M.F. Jhocson Street, Sampaloc, Manila, Metro Manila',
      distance: '350m away',
      imgLoc: 'https://cf.shopee.ph/file/1de15c2041b57d2b984eba80add22419',
   },
]

export default data
