export const donationsData = [
   {
      listingID: 1,
      imgLoc: 'https://cf.shopee.ph/file/1de15c2041b57d2b984eba80add22419',
      donationName: 'Assorted 555 sardines',
      quantity: 5,
      donationCategory: 'Canned Goods',
      donationExpiry: 'July 05, 2021',
      donationNotes: '5 pieces assorted flavor. landmark near SM Marikina',
      pickupLocation:
         'Bali Oasis Condo Phase 1, Marilaque Highway, Pasig, Metro Manila, Philippines',
      pickupDate: 'June 27, 2021',
      //pickupTime: '3:30PM',
      postDateTime: '1hr ago',
      status: 'Posted',
   },
   {
      listingID: 2,
      imgLoc:
         'https://www.seriouseats.com/thmb/Zi-JOQSjIP1lgTkh-qNC4UBsmEk=/1500x1125/filters:fill(auto,1)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2020__02__20200211-cup-noodles-vicky-wasik-3-2f0b82897f5e467589b2e7965105ef96.jpg',
      donationName: 'Nissin Cup Noodles',
      quantity: 7,
      donationCategory: 'Instant Noodles',
      donationExpiry: 'August 15, 2021',
      donationNotes: 'assorted flavor. landmark near SM Marikina',
      pickupLocation:
         'Bali Oasis Condo Phase 1, Marilaque Highway, Pasig, Metro Manila, Philippines',
      pickupDate: 'June 19, 2021',
      //pickupTime: '1:30PM',
      postDateTime: '2hr ago',
      status: 'Ongoing',
   },
   {
      listingID: 3,
      imgLoc:
         'https://ph-test-11.slatic.net/p/83cdc5012a6541bbef182c9eec0fba0e.jpg',
      donationName: 'Butter coconut',
      quantity: 4,
      donationCategory: 'Snacks & Biscuits',
      donationExpiry: 'September 03, 2021',
      donationNotes: '4 pieces only. landmark near SM Marikina',
      pickupLocation:
         'Bali Oasis Condo Phase 1, Marilaque Highway, Pasig, Metro Manila, Philippines',
      pickupDate: 'June 20, 2021',
      //pickupTime: '12:00PM',
      postDateTime: '1d ago',
      status: 'Ongoing',
   },
   {
      listingID: 4,
      imgLoc: 'https://cf.shopee.ph/file/b7feafa6f3bce72377cb7168763ed3bb',
      donationName: 'Nissin Wafer',
      quantity: 6,
      donationCategory: 'Snacks & Biscuits',
      donationExpiry: 'July 27, 2021',
      donationNotes: 'landmark near SM Marikina',
      pickupLocation:
         'Bali Oasis Condo Phase 1, Marilaque Highway, Pasig, Metro Manila, Philippines',
      pickupDate: 'June 17, 2021',
      //pickupTime: '5:00PM',
      postDateTime: '2d ago',
      status: 'Claimed',
   },
   {
      listingID: 9,
      imgLoc: 'https://cf.shopee.ph/file/4626df065c89d76a7d0b6ad567f2d059',
      donationName: '1 tray of egg',
      quantity: 12,
      donationCategory: 'Others',
      donationExpiry: 'November 11, 2021',
      donationNotes: 'landmark near SM Marikina',
      pickupLocation:
         'Bali Oasis Condo Phase 1, Marilaque Highway, Pasig, Metro Manila, Philippines',
      pickupDate: 'June 28, 2021',
      // //pickupTime: '2:00PM',
      postDateTime: '1d ago',
      status: 'Posted',
   },
   {
      listingID: 10,
      imgLoc:
         'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRp_KIe61jOe0l-KeN7CRhjz83I-1_xNgDZLQ&usqp=CAU',
      donationName: 'Nissin eggnog',
      quantity: 3,
      donationCategory: 'Snacks & Biscuits',
      donationExpiry: 'June 25, 2021',
      donationNotes: 'landmark near SM Marikina',
      pickupLocation:
         'Bali Oasis Condo Phase 1, Marilaque Highway, Pasig, Metro Manila, Philippines',
      pickupDate: 'June 15, 2021',
      // //pickupTime: '12:00PM',
      postDateTime: '1w ago',
      status: 'Unposted',
   },
]
